name: Daily News Playlist

on:
  schedule:
    # 09:00 UTC ≈ 06:00 BRT
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests
      - name: Update Spotify playlist
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_USER_ID: ${{ secrets.SPOTIFY_USER_ID }}
        run: |
          python daily_news_playlist.py
